<?php

namespace AppBundle\Repository;

/**
 * AlunnoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlunnoRepository extends \Doctrine\ORM\EntityRepository
{
}
